const {
  NODE_ENV,
  PROD_MONGO_URL,
  DEV_MONGO_URL,
  DEV_ACCESS_TOKEN_SECRET,
  PROD_ACCESS_TOKEN_SECRET,
  DEV_REFRESH_TOKEN_SECRET,
  PROD_REFRESH_TOKEN_SECRET,
  DEV_EMAIL_VERIFICATION_TOKEN_SECRET,
  PROD_EMAIL_VERIFICATION_TOKEN_SECRET,
  DEV_CLIENT_URL,
  PROD_CLIENT_URL,
  DEV_BASE_URL,
  PROD_BASE_URL,
} = process.env;

const IS_PROD_ENVIRONMENT = NODE_ENV === 'PROD' ?? false;

const CLIENT_URL = IS_PROD_ENVIRONMENT ? PROD_CLIENT_URL : DEV_CLIENT_URL;

const BASE_URL = IS_PROD_ENVIRONMENT ? PROD_BASE_URL : DEV_BASE_URL;

const MONGO_URL = IS_PROD_ENVIRONMENT ? PROD_MONGO_URL : DEV_MONGO_URL;

const ACCESS_TOKEN_SECRET = IS_PROD_ENVIRONMENT
  ? PROD_ACCESS_TOKEN_SECRET
  : DEV_ACCESS_TOKEN_SECRET;

const REFRESH_TOKEN_SECRET = IS_PROD_ENVIRONMENT
  ? PROD_REFRESH_TOKEN_SECRET
  : DEV_REFRESH_TOKEN_SECRET;

const EMAIL_VERIFICATION_SECRET = IS_PROD_ENVIRONMENT
  ? PROD_EMAIL_VERIFICATION_TOKEN_SECRET
  : DEV_EMAIL_VERIFICATION_TOKEN_SECRET;

const ALLOWED_ORIGINS = {
  origin: CLIENT_URL,
  credentials: true,
};

module.exports = {
  MONGO_URL,
  ALLOWED_ORIGINS,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  IS_PROD_ENVIRONMENT,
  EMAIL_VERIFICATION_SECRET,
  CLIENT_URL,
  BASE_URL,
};
